### ISSUE TITLE
Branch doesn't contain definition for "EnableLogging"

### ISSUE THREAD

**Issue by kirillivonin** [BranchMetrics/xamarin-branch-deep-linking-attribution#136]
![image](https://user-images.githubusercontent.com/2601010/122771003-ec3c3800-d29d-11eb-959c-5d637665fd65.png)

As Debug mode is being phased out, I can't enable logging anymore as of 7.x Branch Xamarin iOS SDK. As far as I can see from the source, EnableLogging is private and not exposed

**Comment by echo-branch** [comment]
This is in our backlog.

For iOS you can try the following code snippet to enable it.
`
// Enables logging, this is really an ugly way of doing it, need a cleaner API for end users
IOSNativeBranch.Branch tmp = IOSNativeBranch.Branch.GetInstance("your_branch_key");
tmp.EnableLogging();
`

On Android, you could try the following code. But I believe its broken and that's why the shared one didn't make the release.
`
AndroidNativeBranch.EnableLogging();
`

**Comment by kirillivonin** [comment]
Thanks!
